FROM python

WORKDIR '/app'

# The enviroment variable ensures that the python output is set straight
# to the terminal with out buffering it first
# source: https://medium.com/backticks-tildes/how-to-dockerize-a-django-application-a42df0cb0a99
ENV PYTHONUNBUFFERED 1

RUN python3 -m venv django_env
RUN source ./django_env/bin/activate

# Install dependencies
COPY ./requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

# Run startup command
CMD ["npm", "run", "start"]