apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pamgluss-com-tls
spec:
  secretName: pamgluss-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: pamgluss.com
  dnsNames:
    - pamgluss.com
    - www.pamgluss.com
